* OPEN Boot fail on HW if ~debug.serial_log_level~ is 2 or greater
Symptoms:
- kprint at main.zig:142 (inside ~diagnostics~) causes panic with message ~"start index 635284 is larger than end index 8"~
- panic is happening inside the print function for the serial writer.
- is this a concurrency problem?
- I thought this was due to the serial writer not correctly returning the number of bytes written, but have rewritten that section to return actual bytes (it used to just return the string length and assume all bytes wrote ok) and the problem still occurs
* OPEN Flaky boot on HW
Symptoms:
- Stepping through ~kernelInit~ one line at a time via openocd and gdb, boot succeeds and gets to prompt.
- Some lines, like the call to ~diagnostics~ at ~main.zig:80~ result in a corrupted PC
- Timing problem? Interrupts versus the stack?
Resolution:
- Seems like adding memory barriers around the serial interrupt handler helped this.
* OPEN DMA sometimes doesn't complete on HW
Symptoms:
- Using
Repo:
Run the following commands from ~OK>>~
#+begin_src
0 0x4000 fb fb 0x4000 + dma
0 0x4000 fb 0x4000 + fb 0x4000 2 * + dma
#+end_src

The first command copies the 2nd line of the framebuffer over the 1st. (0x4000 is the byte length of one row in the console.)

The second command should copy the 3rd line of the framebuffer over the 2nd.

Multiple ways this can error out:
1. It doesn't complete. ~BroadcomDMAController.awaitChannel~ always sees the DMA as still active.
2. The whole board resets!? (Including reloading kernel from SD card! JTAG still working, but cannot arp halt the CPU!? Weird state!)
