const schedule = @import("../schedule.zig");

pub const Error = error{
    Busy,
    ConfigurationError,
    DataLengthMismatch,
    DeviceDetaching,
    DeviceUnconfigured,
    DeviceUnsupported,
    Failed,
    HardwareError,
    IncorrectDevice,
    InitializationFailure,
    InvalidData,
    InvalidParameter,
    InvalidRequest,
    InvalidResponse,
    NoAvailableChannel,
    NoDevice,
    NotConnected,
    NotProcessed,
    OutOfMemory,
    OvercurrentDetected,
    PowerFailure,
    ResetTimeout,
    TooManyDevices,
    TooManyHubs,
    TransferFailed,
    TransferIncomplete,
    TransferStarted,
    TransferTimeout,
    UnsupportedRequest,
} || schedule.Error;

pub const TransactionStatus = enum {
    ok,
    timeout,
    data_length_mismatch,
    failed,
};
