@startuml
class Request {
        }

class Transfer {
        type
        device_address
        endpoint
}

enum TransferType {
        Control
        Isochronous
        Interrupt
        Bulk
}

class Transaction {
        device_address
        endpoint
}

enum Stage {
        Setup
        Data
        Status
}

class Packet {
}

enum PID {
        OUT
        IN
        SOF
        SETUP
        DATA0
        DATA1
        DATA2
        MDATA
        ACK
        NAK
        NAK
        STALL
        NYET
        PRE
        ERR
        Ping
        "Split"
}

Request "1" -r-> "1" Transfer
Transfer "1" *-r-> "1..*" Transaction
Transfer -u-> TransferType
Transaction -u-> Stage : transaction_stage
Transaction "1" *-r-> "1..*" Packet
Packet -u-> PID : packet_id

note bottom of Request : handled by the application (operating system)
note bottom of Transfer : handled by the host controller driver
note bottom of Transaction : handled by the host controller driver
note bottom of Packet : Handled by the host controller

@enduml
