@startuml
state StartSynchronousTransfer
state StartAsynchronousTransfer
state ChannelAllocated
state AwaitChannelDisable

[*] -d-> StartSynchronousTransfer
[*] -d-> StartAsynchronousTransfer

StartAsynchronousTransfer -d-> SignalAllocated : [signal available] allocate signal
StartAsynchronousTransfer -d-> TransferFailed: [no signal available]

SignalAllocated -l-> StartSynchronousTransfer

StartSynchronousTransfer -d-> ChannelAllocated : [channel available] allocate channel
StartSynchronousTransfer -r-> TransferFailed: [no channel available]

ChannelAllocated : channel assigned

ChannelAllocated --> ChannelAssigned : [channel inactive]
ChannelAllocated --> AwaitChannelDisable : [channel active] disable channel

AwaitChannelDisable -d-> ChannelAssigned : [halted!]
AwaitChannelDisable -> TransferFailed : [timeout] / release channel
AwaitChannelDisable : channel assigned

state ChannelAssigned {
        state StartTransaction
        state AwaitTransactionComplete
        state TransferFailed_withChannel

        [*] -d-> StartTransaction

        StartTransaction: channel assigned
        TransferFailed_withChannel: channel assigned

        StartTransaction -d-> AwaitTransactionComplete : set HCD registers

        AwaitTransactionComplete -l-> WhatDo : [halted!]
        AwaitTransactionComplete -d-> TransferFailed_withChannel : [timeout]
        AwaitTransactionComplete -d-> SynchronousTransferCompleted : [completed! &&\nwas synchronous]
        AwaitTransactionComplete -d-> AsyncTransferCompleted : [completed! &&\nwas asynchronous]
        AwaitTransactionComplete : channel assigned

        WhatDo : channel assigned

        AsyncTransferCompleted -d-> SynchronousTransferCompleted : raise signal
        AsyncTransferCompleted : channel assigned

        TransferFailed_withChannel -d-> [*] : release channel
        SynchronousTransferCompleted -d-> [*] : release channel

        SynchronousTransferCompleted : channel assigned
}

ChannelAssigned -d-> [*] : report success
TransferFailed -> [*] : report error

@enduml
